### ISSUE TITLE
Split manifest parsing from main Manifest struct

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#120]
Currently, the `Manifest` struct (and all of the structs which it references, e.g., `Kong`) is used for parsing/merging the files for a service (e.g., `shipcat.yml`, `dev-uk.yml`) and for representing an assembled/validated manifest for a service (e.g., to write to a CRD).

For the assembled manifest, this means:
* There are backwards-compatibility properties which need to be handled (e.g., the `Kong` has `hosts`, `host` and `uris` properties)
* Defaulted properties are still `Option`s (e.g., `Kong#auth`, so callers need to manually unwrap it to the default value).

For the sources, this means:
* All source files are allowed to be the same shape (e.g., `dev-uk.yml` can define `name`, so that has to be manually validated)
* Adding alternative syntaxes for common features (e.g., allowing `env: { MY_VAR: ~ }` to delete an env var) adds complexity to the Manifest type, which affects the entire codebase.

# Proposal

* `shipcat.yml` and the overrides (e.g., `dev-uk.yml`) are passed as `ServiceDefaults`/`ServiceOverrides`.
  * Simple validation is handled by parser (e.g., there is no `name` field in `ServiceOverrides`, so it's automatically invalid in `dev-uk.yml`)
* The region/global defaults from `shipcat.conf` are parsed as `GlobalDefaults`, `RegionDefaults`.
* The above sources are assembled into a `Manifest`
  * Required properties can be safely obtained from default values `region.replicaCount.or(env.replicaCount).or(service.replicaCount).expect("replicaCount is required") (we'd probably want a nicer syntax).
  * Additional validation (e.g., env vars are upper case) are also performed
  * More complex conversion occurs (e.g., parsing env var templates)
* `Manifest` structs are passed to the rest of Shipcat
  * They are always valid (e.g., required properties are not `Option`s)
  * Only high level validation (e.g., is a secret missing) is performed by commands.

_I'm not convinced with the above naming conventions, open to suggestions._

**Comment by clux** [comment]
Yeah, that will take away a lot of the magic 50+ `option.unwrap()` calls that is guaranteed by verify, which would definitely make the codebase nicer. I strayed away from it initially because it felt like everything in what is `Manifest` had to be duplicated on what you call `ServiceOverrides` as optionals anyway.

The kong host/hosts issue is a bit messy. Definitely some of those fields should live in a `gate:` syntax that Themis started, as they don't really related to kong at all.

I can see the benefit for getting a clear distinction between what is an Optional vector vs. a missing vector, a lot of which relies on serde annotations atm. But how would you get the benefit within a top struct like `kong`? How do you get around optionals __within__ that?

How would this help your example of `env: { MY_VAR: ~ }`? This feels like it would complex anyway, but maybe I'm missing something.

aside: I was always hoping it was possible to make `merge` something defineable on the struct itself, rather relying on filling in a list in` merge.rs` with special case `implicts`

**Comment by janslow** [comment]
For, Kong, I'd probably have multiple structs: a `KongSource` which is parsed from a file and a `Kong` which is the simplified/assembled version.

That would also allow you to have regional/global defaults easily as well.

For the env vars, you could have the source type being a `Map<String, Option<String>>` and merging that down to `Map<String, String>` (e.g, when you're trying to get rid of an old environment variable). Assuming serde is happy parsing it.

**Comment by clux** [comment]
Yeah, that makes more sense. Serde should be happy about that. It should also fix the unfortunate coercion of:
```
env:
  SOMEENV: ~
```
into `SOMEENV: "~"`

`KongSource` makes sense for `Kong`, but probably not most other things. Still, it would be a improvement for it for sure.

**Comment by janslow** [comment]
In terms of source code structure, I was thinking of adding a `shipcat_definitions/src/filebacked` directory (which would depend on shipcat_definitions/src/structs` and probably `shipcat_definitions/src`).

Most structs in there will be `pub(self)`, probably only exposing a method like [`ManifestSource`](https://github.com/Babylonpartners/shipcat/blob/master/shipcat_definitions/src/filebacked.rs#L13) to other modules, which would replace most/all of the `Manifest::base` functionality.

Alternatively, we could have an entirely separate `shipcat_filebacked` crate which depends on `shipcat_definitions`.

**Comment by janslow** [comment]
For struct naming, the following pattern should be good enough:

* `Manifest` representing an assembled/validated Shipcat manifest
* `ManifestSource` as the struct to parse from a service's `shipcat.yml`/region override
  * It should be possible to create a `Manifest` from a single `ManifestSource` (e.g., if everything is defined by the service)
* `ManifestDefaults` as the struct to parse from the `defaults` property or a region in `shipcat.conf`
  * Shouldn't allow service-specific values (e.g., no `metadata` property)
  * May be a type alias for `ManifestSource`, if there are no difference

**Comment by clux** [comment]
This should be closed now, no?
